# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Adastra_test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Adastra_test

pod 'KeyboardDismisser'
pod 'EmptyDataSet-Swift', '~> 4.0.5'

end
